{% set name = "jupytext" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8627dd9becbbebd79cc4a4ed4727d89d78e606b4b464eab72357b3b029023a14

build:
  number: 1
  entry_points:
    - jupytext = jupytext.cli:jupytext
    - jupytext-config = jupytext_config.__main__:main
  noarch: python
  script: HATCH_BUILD_HOOKS_ENABLE=true {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python >=3.8,<3.12
    - python-build
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.5.0
    - pip
  run:
    - python >=3.8
    - nbformat
    - mdit-py-plugins
    - markdown-it-py >=1.0
    - packaging
    - pyyaml
    - tomli;python_version <"3.11"

test:
  imports:
    - jupytext
  commands:
    - jupytext --help
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-jupytext/package.json                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-jupytext\\package.json (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/mwouts/jupytext
  doc_url: https://github.com/mwouts/jupytext/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts
  description: |
    Represent Jupyter notebooks as Markdown documents or Julia, Python or R scripts. Convert any
    script or Markdown document to a Jupyter notebook. Round trip conversion is robust and well tested.

    Use these simpler representations to do version control and collaborate on Jupyter notebooks.
    And refactor your notebooks encoded as scripts in your favorite IDE.

    Jupytext is available directly in Jupyter Notebook and JupyterLab, and also on the command line.

extra:
  recipe-maintainers:
    - grst
    - mwouts
