{% set name = "jupytext" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94c7e67775e90e1792c39ab7fca4e0459bf7c35656123e8dc2e9e1b3e953baf8

build:
  number: 0
  entry_points:
    - jupytext = jupytext.cli:jupytext
    - jupytext-config = jupytext_config.__main__:main
  noarch: python
  script: python -m build

requirements:
  host:
    - python >=3.8
    - pip
    - build
    - wheel
    - nodejs
    - jupyterlab >=4.0
  run:
    - python >=3.8
    - nbformat
    - mdit-py-plugins
    - markdown-it-py >=1.0
    - packaging
    - pyyaml
    - toml

test:
  imports:
    - jupytext
  commands:
    - jupytext --help
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-jupytext/package.json                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-jupytext\\package.json (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/mwouts/jupytext
  doc_url: https://github.com/mwouts/jupytext/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts
  description: |
    Represent Jupyter notebooks as Markdown documents or Julia, Python or R scripts. Convert any
    script or Markdown document to a Jupyter notebook. Round trip conversion is robust and well tested.

    Use these simpler representations to do version control and collaborate on Jupyter notebooks.
    And refactor your notebooks encoded as scripts in your favorite IDE.

    Jupytext is available directly in Jupyter Notebook and JupyterLab, and also on the command line.

extra:
  recipe-maintainers:
    - grst
    - mwouts
