{% set name = "jupytext" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a32aa9edbc430653de3149de79c4ff4ee33ded2119b41ed476b5c93c9f6aff1

build:
  number: 0
  entry_points:
    - jupytext = jupytext.cli:jupytext
  noarch: python
  script: BUILD_JUPYTERLAB_EXTENSION=1 {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - python
    - nodejs
    - jupyter-packaging
    - jupyterlab >=3.0
  run:
    - python >=3.6
    - nbformat
    - pyyaml
    - toml
    - markdown-it-py >=1.0,<2.0

test:
  imports:
    - jupytext
  commands:
    - jupytext --help
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupytext/index.js                                              # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-jupytext/package.json                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupytext\\index.js (exit 0) else (exit 1)                  # [win]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-jupytext\\package.json (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/mwouts/jupytext
  doc_url: https://github.com/mwouts/jupytext/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts
  description: |
    Represent Jupyter notebooks as Markdown documents or Julia, Python or R scripts. Convert any
    script or Markdown document to a Jupyter notebook. Round trip conversion is robust and well tested.

    Use these simpler representations to do version control and collaborate on Jupyter notebooks.
    And refactor your notebooks encoded as scripts in your favorite IDE.

    Jupytext is available directly in Jupyter Notebook and JupyterLab, and also on the command line.

extra:
  recipe-maintainers:
    - grst
    - mwouts
