{% set name = "jupytext" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4605d053c0cfc4562a936033d14355cd2fbc44d81afc90629e32c00e2d28615

build:
  number: 0
  entry_points:
    - jupytext = jupytext.cli:jupytext
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - pip
    - python
  run:
    - nbformat >=4.0.0
    - pyyaml
    - toml

test:
  imports:
    - jupytext
  commands:
    - jupytext --help

about:
  home: https://github.com/mwouts/jupytext
  doc_url: https://github.com/mwouts/jupytext/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts
  description: |
    Represent Jupyter notebooks as Markdown documents or Julia, Python or R scripts. Convert any
    script or Markdown document to a Jupyter notebook. Round trip conversion is robust and well tested.

    Use these simpler representations to do version control and collaborate on Jupyter notebooks.
    And refactor your notebooks encoded as scripts in your favorite IDE.

    Jupytext is available directly in Jupyter Notebook and JupyterLab, and also on the command line.

extra:
  recipe-maintainers:
    - grst
    - mwouts
